# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

# app/config/config.yml
fos_ck_editor:
    input_sync: true
    default_config: advanced_config
    configs:
        clear_config:
            width: '100%'
            toolbar:
        advanced_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'BulletedList', 'Link'] }

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
