parameters:
    logo_upload_destination: '%kernel.project_dir%/public/images/logo'
vich_uploader:
    db_driver: orm

    mappings:
        site_logo:
            uri_prefix: /images/logo
            upload_destination: '%logo_upload_destination%'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
