imports: 
    - { resource: a2lix.yaml }
    - { resource: easy_admin.yaml }
    - { resource: fos_ckeditor.yaml }
    - { resource: knp_doctrine_behaviors.yaml }
    - { resource: stof_doctrine_extensions.yaml }
    - { resource: vich_uploader.yaml }
    - { resource: webpack_encore.yaml }
    - { resource: twig.yaml }
parameters:
    locale: fr
services:
    
    ###
    # Constraint Validator
    ###
    Hubsine\SkeletonBundle\Validator\Constraints\UniqueEntryValidator:
        #resource: '../../../Validator/Constraints/*Validator'
        tags: ['validator.constraint_validator']
        arguments:
            $registry: '@doctrine'
            
    ###
    # Repository
    ###
    Hubsine\SkeletonBundle\Repository\:
        resource: '../../../Repository/*'
        tags: ['doctrine.repository_service']
        arguments:
            $registry: '@doctrine'
        
    ###
    # Doctrine Table Prefix
    ###
    Hubsine\SkeletonBundle\EventSubscriber\TablePrefixSubscriber:
        arguments:
            $prefix: 'hubsine_skeleton_'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            
    ###
    # Custom File Namer
    ###
    Hubsine\SkeletonBundle\Naming\:
        resource: '../../../Naming/'
        public: true
               
    ###
    # SiteVariable
    ###
    Hubsine\SkeletonBundle\Twig\SkeletonVariable:
        arguments:
            $doctrine: '@doctrine'
        