imports: 
    - { resource: a2lix.yaml }
    - { resource: easy_admin.yaml }
    - { resource: fos_ckeditor.yaml }
    - { resource: knp_doctrine_behaviors.yaml }
    - { resource: stof_doctrine_extensions.yaml }
    - { resource: vich_uploader.yaml }
    - { resource: webpack_encore.yaml }
    - { resource: twig.yaml }
    - { resource: fos_user.yaml }
    - { resource: security.yaml }
    - { resource: fm_elfinder.yaml }