imports: 
    - { resource: easy_admin.yaml }
    - { resource: fos_ckeditor.yaml }
    - { resource: knp_doctrine_behaviors.yaml }
    - { resource: stof_doctrine_extensions.yaml }
    - { resource: vich_uploader.yaml }
    - { resource: webpack_encore.yaml }
parameters:
    locale: fr
services:
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Hubsine\SkeletonBundle\EventSubscriber\TablePrefixSubscriber:
        arguments:
            $prefix: 'hubsine_skeleton_'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
            
    ###
    # Custom File Namer
    ###
    Hubsine\SkeletonBundle\Naming\:
        resource: '../../../Naming/'
        public: true
               