parameters:
    logo_upload_destination: '%kernel.project_dir%/public/uploads/appearance'
vich_uploader:
    db_driver: orm

    mappings:
        site_appearance:
            uri_prefix: /uploads/appearance
            upload_destination: '%logo_upload_destination%'
            namer: Hubsine\SkeletonBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
