parameters:
    locale: fr
    
services:
    
    ###
    # Constraint Validator
    ###
    Hubsine\SkeletonBundle\Validator\Constraints\UniqueEntryValidator:
        tags: ['validator.constraint_validator']
        public: false
        arguments:
            $registry: '@doctrine'
          
       
    hubsine_skeleton.validator.unique_entry:
        alias: Hubsine\SkeletonBundle\Validator\Constraints\UniqueEntryValidator
        public: true
        
    ###
    # Repository
    ###
    Hubsine\SkeletonBundle\Repository\:
        resource: '../../Repository/*'
        tags: ['doctrine.repository_service']
        arguments:
            $registry: '@doctrine'
            
    ###
    # EVENT SUBSCRIBER
    ###
    
    Hubsine\SkeletonBundle\EventSubscriber\TablePrefixSubscriber:
        arguments:
            $prefix: 'hubsine_skeleton_'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        public: false    
            
    Hubsine\SkeletonBundle\EventSubscriber\MaintenanceSubscriber:
        arguments:
            $doctrine: '@doctrine'
            $authorizationChecker: '@security.authorization_checker'
            $tokenStorage: '@security.token_storage'
            $twig: '@twig'
            $env: '%env(string:APP_ENV)%'
        tags: ['kernel.event_subscriber']
        public: false
        
    hubsine_skeleton.event_subscriber.table_prefix:
        alias: Hubsine\SkeletonBundle\EventSubscriber\TablePrefixSubscriber
        public: true
            
    hubsine_skeleton.event_subscriber.maintenance:
        alias: Hubsine\SkeletonBundle\EventSubscriber\MaintenanceSubscriber
        public: true            
      
    ###
    # Custom File Namer
    ###
    Hubsine\SkeletonBundle\Naming\SmartUniqueNamer:
        public: false
        
    hubsine_skeleton.naming.smart_unique_namer:
        alias: Hubsine\SkeletonBundle\Naming\SmartUniqueNamer
        public: true
        
    ###
    # SiteVariable
    ###
    Hubsine\SkeletonBundle\Twig\SkeletonVariable:
        public: false
        arguments:
            $doctrine: '@doctrine'
            $eventDispatcher: '@event_dispatcher'
    hubsine_skeleton.twig.variable:
        public: true
        alias: Hubsine\SkeletonBundle\Twig\SkeletonVariable
        
    ###
    # SkeletonMailer
    ###
    swiftmailer.mailer.skeleton.transport:
        class: Swift_SmtpTransport
    swiftmailer.mailer.skeleton:
        public: true
        class: Hubsine\SkeletonBundle\Mailer\SkeletonMailer
        arguments:
            $doctrine: '@doctrine'
            $transport: '@swiftmailer.mailer.skeleton.transport'
        
    

