easy_admin:
    design:
        menu:
            # Users
            - { label: Appearance }
            - { entity: Site, label: 'Site' }
            - { entity: Logo, label: Logo }
            - { entity: SocialNetwork, label: 'Réseaux sociaux' }
    entities:
        Site:
            class: Hubsine\SkeletonBundle\Entity\Appearance\Site
            disabled_actions: []
            list:
                fields: 
                    - name
                    - slogan
                    - description
            form:
                fields:
                    - name
                    - { property: 'translations', label: false, type: A2lix\TranslationFormBundle\Form\Type\TranslationsType,
                        type_options: 
                        {
                            default_locale: '%locale%',
                            fields: 
                            {
                                slogan: { field_type: 'Symfony\Component\Form\Extension\Core\Type\TextType' },
                                description: { field_type: 'FOS\CKEditorBundle\Form\Type\CKEditorType' }
                            }
                        }
                        }
            new:
                form_options: { validation_groups: ['Default', 'create'] }
        Logo:
            class: Hubsine\SkeletonBundle\Entity\Appearance\Logo
            list:
                fields:
                    - { property: name, template: 'EasyAdmin/vich_uploader_image.html.twig' }
            form:
                fields:
                    - { property: file, type: 'vich_image', base_path: '%app.directory.logo%' }
            new:
                form_options: { validation_groups: ['Default', 'create'] }
        SocialNetwork:
            class: Hubsine\SkeletonBundle\Entity\Appearance\SocialNetwork
            