easy_admin:
    design:
        menu:
            # Users
            - { label: Appearance }
            - { entity: Site, label: 'Site' }
            - { entity: Logo, label: Logo }
    entities:
        Site:
            class: Hubsine\SkeletonBundle\Entity\Appearance\Site
            disabled_actions: []
            list:
                fields: 
                    - name
                    - slogan
                    - description
            form:
                fields:
                    - name
            new:
                form_options: { validation_groups: ['Default', 'create'] }
        SiteTranslation:
            class: Hubsine\SkeletonBundle\Entity\Appearance\SiteTranslation
            disabled_actions: []
            list:
                fields: 
                    - slogan
                    - description
            form:
                fields:
                    - { property: locale }
                    - { property: slogan }
                    - { property: description, type: 'fos_ckeditor', type_options: { config_name: 'clear_config' } }
        Logo:
            class: Hubsine\SkeletonBundle\Entity\Appearance\Logo
            list:
                fields:
                    - { property: name, template: 'EasyAdmin/vich_uploader_image.html.twig' }
            form:
                fields:
                    - { property: file, type: 'vich_image', base_path: '%app.directory.logo%' }
            new:
                form_options: { validation_groups: ['Default', 'create'] }