easy_admin:
    entities:
        Site:
            class: App\Entity\Site
            disabled_actions: []
            list:
                fields: 
                    - name
                    - slogan
                    - descrip